# Generated by Django 4.2.1 on 2023-05-06 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infotj_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='establishment_photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='image',
        ),
        migrations.AddField(
            model_name='establishment',
            name='type_of_establishment',
            field=models.CharField(choices=[('M', 'Медицина'), ('P', 'Парки и места отдыха'), ('K', 'Культура и кино'), ('S', 'Покупка'), ('A', 'Авто'), ('U', 'Учёба'), ('F', 'Питание')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EstablishmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infotj_app.establishment')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infotj_app.photo')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='photos',
            field=models.ManyToManyField(related_name='establishments', through='infotj_app.EstablishmentPhoto', to='infotj_app.photo'),
        ),
    ]
